import type { GlobalThemeOverrides } from 'naive-ui'

function token(name: string, fallback = ''): string {
  if (typeof window === 'undefined') {
    return fallback
  }

  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  return value || fallback
}

export function buildNaiveThemeOverrides(): GlobalThemeOverrides {
  return {
    common: {
      baseColor: token('--bg'),
      primaryColor: token('--accent'),
      primaryColorHover: token('--accent-strong'),
      primaryColorPressed: token('--accent-press'),
      primaryColorSuppl: token('--accent-strong'),
      infoColor: token('--info'),
      successColor: token('--success'),
      warningColor: token('--warning'),
      errorColor: token('--danger'),
      textColorBase: token('--text'),
      textColor1: token('--text'),
      textColor2: token('--text-2'),
      textColor3: token('--text-muted'),
      textColorDisabled: token('--text-faint'),
      placeholderColor: token('--text-faint'),
      placeholderColorDisabled: token('--text-faint'),
      iconColor: token('--text-muted'),
      iconColorHover: token('--text'),
      iconColorPressed: token('--text-2'),
      iconColorDisabled: token('--text-faint'),
      dividerColor: token('--border-strong'),
      borderColor: token('--border'),
      bodyColor: token('--bg'),
      cardColor: token('--surface'),
      modalColor: token('--surface'),
      popoverColor: token('--surface'),
      tableColor: token('--surface'),
      inputColor: token('--surface'),
      inputColorDisabled: token('--surface-2'),
      actionColor: token('--surface-2'),
      hoverColor: token('--state-hover-bg'),
      pressedColor: token('--state-active-bg'),
      tableHeaderColor: token('--surface-2'),
      tableColorHover: token('--state-hover-bg'),
      tableColorStriped: token('--surface-2'),
      tagColor: token('--surface-2'),
      avatarColor: token('--surface-2'),
      buttonColor2: token('--surface-2'),
      buttonColor2Hover: token('--state-hover-bg'),
      buttonColor2Pressed: token('--state-active-bg'),
      boxShadow1: token('--shadow-sm'),
      boxShadow2: token('--shadow-md'),
      boxShadow3: token('--shadow-lg'),
      fontFamily: token('--font-sans'),
      fontFamilyMono: token('--font-mono'),
      fontSize: token('--fs-base'),
      fontSizeSmall: token('--fs-sm'),
      fontSizeMedium: token('--fs-base'),
      fontSizeLarge: token('--fs-lg'),
      borderRadius: token('--r-sm'),
      borderRadiusSmall: token('--r-xs'),
      heightSmall: token('--control-h-sm'),
      heightMedium: token('--control-h'),
    },
    Button: {
      textColorPrimary: token('--text-on-accent'),
      textColorHoverPrimary: token('--text-on-accent'),
      textColorPressedPrimary: token('--text-on-accent'),
      textColorFocusPrimary: token('--text-on-accent'),
      colorSecondary: token('--surface-2'),
      colorSecondaryHover: token('--state-hover-bg'),
      colorSecondaryPressed: token('--state-active-bg'),
      borderRadiusSmall: token('--r-xs'),
      borderRadiusMedium: token('--r-sm'),
      borderRadiusLarge: token('--r-md'),
      fontSizeSmall: token('--fs-sm'),
      fontSizeMedium: token('--fs-base'),
      fontSizeLarge: token('--fs-lg'),
      heightSmall: token('--control-h-sm'),
      heightMedium: token('--control-h'),
    },
    Card: {
      color: token('--surface'),
      colorModal: token('--surface'),
      colorPopover: token('--surface'),
      textColor: token('--text'),
      titleTextColor: token('--text'),
      borderColor: token('--border'),
      actionColor: token('--surface-2'),
      boxShadow: token('--shadow-sm'),
      borderRadius: token('--r-md'),
      paddingMedium: token('--s-4'),
    },
    Dialog: {
      color: token('--surface'),
      textColor: token('--text'),
      titleTextColor: token('--text'),
      iconColor: token('--text-muted'),
      iconColorInfo: token('--info'),
      iconColorSuccess: token('--success'),
      iconColorWarning: token('--warning'),
      iconColorError: token('--danger'),
      borderRadius: token('--r-md'),
    },
    Dropdown: {
      color: token('--surface'),
      dividerColor: token('--border-strong'),
      optionColorHover: token('--state-hover-bg'),
      optionColorActive: token('--accent-bg'),
      optionTextColor: token('--text'),
      optionTextColorHover: token('--text'),
      optionTextColorActive: token('--accent-strong'),
      borderRadius: token('--r-sm'),
    },
    Input: {
      color: token('--surface'),
      colorFocus: token('--surface'),
      colorDisabled: token('--surface-2'),
      textColor: token('--text'),
      textColorDisabled: token('--text-faint'),
      placeholderColor: token('--text-faint'),
      placeholderColorDisabled: token('--text-faint'),
      caretColor: token('--accent'),
      loadingColor: token('--accent'),
      boxShadowFocus: token('--state-focus-ring'),
    },
    Menu: {
      color: token('--surface'),
      dividerColor: token('--border-strong'),
      itemColorHover: token('--state-hover-bg'),
      itemColorActive: token('--accent-bg'),
      itemColorActiveHover: token('--accent-bg-2'),
      itemTextColor: token('--text'),
      itemTextColorHover: token('--text'),
      itemTextColorActive: token('--accent-strong'),
      itemTextColorActiveHover: token('--accent-strong'),
      itemIconColor: token('--text-muted'),
      itemIconColorHover: token('--text'),
      itemIconColorActive: token('--accent-strong'),
      itemIconColorActiveHover: token('--accent-strong'),
      arrowColor: token('--text-muted'),
      arrowColorHover: token('--text'),
      arrowColorActive: token('--accent-strong'),
      arrowColorActiveHover: token('--accent-strong'),
      groupTextColor: token('--text-muted'),
      borderRadius: token('--r-xs'),
      fontSize: token('--fs-base'),
    },
    Modal: {
      color: token('--surface'),
      textColor: token('--text'),
      boxShadow: token('--shadow-lg'),
    },
    Popover: {
      color: token('--surface'),
      dividerColor: token('--border-strong'),
      textColor: token('--text'),
      boxShadow: token('--shadow-md'),
      borderRadius: token('--r-sm'),
      fontSize: token('--fs-sm'),
    },
    Slider: {
      railColor: token('--surface-2'),
      railColorHover: token('--surface-3'),
      fillColor: token('--accent'),
      fillColorHover: token('--accent-strong'),
      handleBoxShadowFocus: token('--state-focus-ring'),
    },
    Switch: {
      railColor: token('--surface-2'),
      railColorActive: token('--accent'),
      boxShadowFocus: token('--state-focus-ring'),
    },
    Tabs: {
      colorSegment: token('--surface-2'),
      tabTextColorLine: token('--text-muted'),
      tabTextColorActiveLine: token('--accent'),
      tabTextColorHoverLine: token('--accent-strong'),
      tabTextColorDisabledLine: token('--text-faint'),
      tabColor: token('--surface'),
      tabColorSegment: token('--surface'),
      tabBorderColor: token('--border'),
      tabBorderRadius: token('--r-sm'),
      paneTextColor: token('--text'),
      barColor: token('--accent'),
      closeColorHover: token('--state-hover-bg'),
      closeColorPressed: token('--state-active-bg'),
      closeBorderRadius: token('--r-xs'),
    },
  }
}
